// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf79vNkKUggw91AGFeNEo76uM8V-asaNo',
    appId: '1:891201875410:android:c8c7cbb737db27fd11ec0b',
    messagingSenderId: '891201875410',
    projectId: 'mooc-kinane-eba27',
    storageBucket: 'mooc-kinane-eba27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjdvJP5A44IfZagswTidMwZAhXxlXMliA',
    appId: '1:891201875410:ios:977c09f3afb5ad2911ec0b',
    messagingSenderId: '891201875410',
    projectId: 'mooc-kinane-eba27',
    storageBucket: 'mooc-kinane-eba27.appspot.com',
    androidClientId: '891201875410-r329ulilmg8g6gc9vupf46hbes1t8huk.apps.googleusercontent.com',
    iosClientId: '891201875410-rqbvfhmrcmgp6n7bu8rrao6e1ned0bh5.apps.googleusercontent.com',
    iosBundleId: 'com.codevit.baseApp',
  );
}
